name: Github Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      env:
        ANSIBLE_LOG_PATH: ${{ runner.temp }}/logs/ansible.log
      - run: env | sort
