name: Github Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        env:
          ANSIBLE_LOG_PATH: ${{ runner.temp }}/logs/ansible.log
        run: env | sort
      - name: check env
        run: env | sort
